name: wltapp
on:
    push:
        branches:
            - master
jobs:
    build:
        env:
            THE_GH_TOKEN: ${{ secrets.THE_GH_TOKEN }}
            VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
            VITE_APP_APP_ID: ${{ secrets.VITE_APP_APP_ID }}
            VITE_APP_MESSAGING_SENDER_ID: ${{ secrets.VITE_APP_MESSAGING_SENDER_ID }}
            VITE_APP_PROJECT_ID: ${{ secrets.VITE_APP_PROJECT_ID }}
            VITE_APP_AUTH_DOMAIN: ${{ secrets.VITE_APP_AUTH_DOMAIN }}
            VITE_APP_STORAGE_BUCKET: ${{ secrets.VITE_APP_STORAGE_BUCKET }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Packages
              run: npm install
            - name: Deploy to GH Pages
              run: |
                  git config --global user.email coalovaboris@gmail.com
                  git config --global user.name bcoalova
                  git remote set-url origin https://${{secrets.THE_GH_TOKEN}}@github.com/BCoalova/wltapp.git
                  npm run deploy
